
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/components/StoreProvider";
import Navbar from "@/components/admin/navbar";

 
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <div className="flex">
            <Navbar className="min-w-[260px] h-[100vh] shadow-md flex-none sticky top-0 bg-shade-light"/>
              <div className=" grow rounded-lg bg-[#F8FAFC] overflow-auto">
              {children}
              </div>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
